### PR TITLE
Update versions of dependencies

### PR DESCRIPTION
**Pull request by cqc-alec**

### CODE REVIEW

**Review by ss2165 — APPROVED** [review]

**Comment by ss2165** [comment]
so do the doctests work or do they need changing?

**Comment by cqc-alec** [comment]
> so do the doctests work or do they need changing?

The problem is with a doctest in pytket-pennylane itself, invoked from [here](https://github.com/CQCL/pytket-pennylane/blob/21e6558218509350ac268eade87ed6cef037d395/tests/run_pennylane_tests.py#L13). The failing doctest seems to be [this one](https://github.com/PennyLaneAI/pennylane/blob/3710433d3bbbb7f6f92fc8a478cbaadabc646616/pennylane/devices/tests/__init__.py#L123), and I believe the culprit is [this line](https://github.com/PennyLaneAI/pennylane/blob/3710433d3bbbb7f6f92fc8a478cbaadabc646616/pennylane/devices/tests/pytest.ini#L4), which specifies an argument that is not supported in latest pytest.

**Comment by cqc-alec** [comment]
@ss2165 Are you happy for this to be merged?

**Review by ss2165 — APPROVED** [review]
yes!

**Pull request merged**
