### PR TITLE
update ci workflows to run weekly

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by cqc-melf** [comment]
Should be the same PR as for pytket-aqt

**Comment by cqc-melf** [comment]
Can we maybe think about activating auto merge here, too?

**Comment by cqc-alec** [comment]
> Can we maybe think about activating auto merge here, too?

Not a big fan of automerge personally.

**Review by cqc-alec — APPROVED** [review]

**Comment by cqc-melf** [comment]
> > Can we maybe think about activating auto merge here, too?
> 
> Not a big fan of automerge personally. But if you like we can.

I have only started using them for already discussed PRs like this one on the other repos, maybe this is a useful case?

**Pull request merged**
